theme: jekyll-theme-cayman
title: "Dinneth's blog 测试中文和即时刷新是否 work"

author:
  name             : "丁"
  avatar           : "https://tva2.sinaimg.cn/crop.0.0.180.180.180/6e471a1djw1e8qgp5bmzyj2050050aa8.jpg"
